import type { Metadata } from 'next';
import { Aclonica, Montserrat } from 'next/font/google';
import NavBar from './components/navBar/Navbar';
import './globals.css';
const aclonica = Aclonica({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-aclonica',
});
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: '600',
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={` ${aclonica.className} bg-gradient-to-b from-navbar via-navbar to-transparent`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
